CREATE TABLE Medico.doctor (
  ID_DOCTOR INT AUTO_INCREMENT NOT NULL,
  DOCTOR_NAME VARCHAR(100) NOT NULL,
  DOCTOR_EMAIL VARCHAR(100) NOT NULL,
  CONSTRAINT PK_doctor PRIMARY KEY (ID_DOCTOR)
);

--Necessario inserir doutores
INSERT INTO `medico`.`doctor`
(`ID_DOCTOR`,`DOCTOR_NAME`,`DOCTOR_EMAIL`)
VALUES
(5,'Rafael Costa Neto', 'rafael.neto27@gmail.com');
INSERT INTO `medico`.`doctor`
(`ID_DOCTOR`,`DOCTOR_NAME`,`DOCTOR_EMAIL`)
VALUES
(2,'Dayane Oliveira Nascimento', 'dayane.nscimento01@hotmail.com');
INSERT INTO `medico`.`doctor`
(`ID_DOCTOR`,`DOCTOR_NAME`,`DOCTOR_EMAIL`)
VALUES
(3,'João Batista Ferreira', 'joao39@outlook.com');

CREATE TABLE Medico.user (
  IDUSER INT AUTO_INCREMENT NOT NULL,
  USER_NAME VARCHAR(100) NOT NULL,
  USER_PASSWORD VARCHAR(40) NOT NULL,
  USER_EMAIL VARCHAR(100) NOT NULL,
  CONSTRAINT PK_user PRIMARY KEY (IDUSER)
);

CREATE TABLE Medico.specialty (
  ID_SPECIALTY INT AUTO_INCREMENT NOT NULL,
  ID_SPECIALTY_DOCTOR INT NOT NULL,
  SPECIALTY_DESCRIPTION VARCHAR(50),
  CONSTRAINT PK_specialty PRIMARY KEY (ID_SPECIALTY)
);

ALTER TABLE Medico.specialty
  ADD CONSTRAINT FK_specialty_doctor
  FOREIGN KEY (ID_SPECIALTY_DOCTOR) REFERENCES Medico.doctor (ID_DOCTOR);
  
CREATE TABLE Medico.appointment (
  ID_APPOINTMENT INT AUTO_INCREMENT NOT NULL,
  ID_APPOINTMENT_DOCTOR INT NOT NULL,
  ID_APPOINTMENT_USER INT NOT NULL,
  DESCRIPTION VARCHAR(145),
  CREATION_DATE DATETIME,
  CONSTRAINT PK_appointment PRIMARY KEY (ID_APPOINTMENT)
);

ALTER TABLE Medico.appointment
  ADD CONSTRAINT FK_appointment_doctor
  FOREIGN KEY (ID_APPOINTMENT_DOCTOR) REFERENCES Medico.doctor (ID_DOCTOR);

ALTER TABLE Medico.appointment
  ADD CONSTRAINT FK_appointment_user
  FOREIGN KEY (ID_APPOINTMENT_USER) REFERENCES Medico.user (IDUSER);




